bump_version: null
lint:
  files_unchanged:
    - assets/sendmail_template.txt
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Harshil Patel
  description: Image Mass Cytometry analysis pipeline.
  force: false
  is_nfcore: true
  name: imcyto
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.1.0dev
update: null
