FROM nfcore/base
LABEL authors="Harshil Patel" \
      description="Docker image containing Ilastik requirements for nf-core/imcyto pipeline"

COPY environment_ilastik.yml /
RUN conda env create -f /environment_ilastik.yml && conda clean -a
ENV PATH /opt/conda/envs/nf-core-imcyto-ilastik-1.0dev/bin:$PATH
RUN alias run_ilastik.sh='/opt/conda/envs/nf-core-imcyto-ilastik-1.0dev/run_ilastik.sh'
